### PR TITLE
Update wrench dependency. Fixes #104

### LINKED ISSUE #104: Fails when a package is bower linked
If you `bower link <package>` the package fails to install.

### PR DESCRIPTION
**Pull request by xzyfer**
This fixes a bug where trying to copy a bower linked package throws an error

### CODE REVIEW

**Comment by yatskevich** [comment]
@xzyfer Great, thanks! Will merge it over the weekend.

**Comment by xzyfer** [comment]
Any progress on this?

**Comment by codewithtyler** [comment]
@yatskevich so looking over the [wrench package](https://www.npmjs.com/package/wrench) it looks like it's no longer updated and the project owner recommends switching to the [fs-extra](https://github.com/jprichardson/node-fs-extra) package. What do you think?

**Comment by yatskevich** [comment]
@RandomlyKnighted sure, let's switch to fs-extra!

**Pull request merged**
