### PR TITLE
multiple bower files

### PR DESCRIPTION
**Pull request by alexander-akait**
Example

``` javascript
bower: {
  buildDev: {
    options: {
      argetDir: './',
      install: true,
      cleanTargetDir: false,
      verbose: true,
      cleanBowerDir: true,
      layout: 'byComponent',
        bowerOptions: {
          forceLatest: true,
          production: false
        }
    },
    src: [
      '**/bower.json',
      '!**/node_modules/**/*',
      '!**/bower_components/**/*'
    ]
  }
}
```

### CODE REVIEW

**Comment by linkesch** [comment]
Thumbs up! This is a godsend.

**Comment by yatskevich** [comment]
@sheo13666 thanks a lot for the contribution! Could you please provide tests for this feature?

**Comment by alexander-akait** [comment]
@yatskevich Sorry, i have no time for writing tests now

**Comment by alexander-akait** [comment]
afterCopyCallback

**Comment by jiminikiz** [comment]
If I write the tests, would you pull this feature in?

**Comment by alexander-akait** [comment]
soon I shall add more functionality when there is a problem with the ways (in css, js, html, less and etc) during installation

**Comment by codewithtyler** [comment]
Thank you for your contribution; however, I've talked with @yatskevich and we currently have no plans to support multiple bower.json files at this time. If at some point we get a lot of requests for this we will reconsider adding this feature.

**Pull request closed without merging**
