### PR TITLE
AssetCopier should use pkg then type

### PR DESCRIPTION
**Pull request by robdodson**
Bower installs everything namespaced by the pkg. This is also how npm works.
It's really weird for everything to end up in a types folder first, then namespaced by the pkg.

Example:

```
less/bootstrap
```

I think having it the other way around would make more sense and it's probably how bower's `main` property is going to work once they implement it.

```
bootstrap/less
```

### CODE REVIEW

**Comment by Iristyle** [comment]
I would suggest leaving off afdad43.

Instead use npm shrinkwrap if you're trying to lock down package versions.

**Comment by yatskevich** [comment]
@robdodson, thanks for your effort! In fact grouping _by type_ is intentional. 

I'd like to be able to specify _one_ root directory with 3rd party libraries for SASS compiler in order to use simple imports in my SASS files:
**Gruntfile.js**

``` js
sass: {
  compile: {
    options: {
      loadPath: [ 'lib/scss', 'assets/stylesheets' ]
    }
  }
}
```

**example.scss**

``` less
@import "bootstrap-sass/mixins";
```

If you need a different target locations then let's figure out a configurable way of doing this.

**Comment by robdodson** [comment]
@Iristyle oops I should have branched first. I included the node_modules because I'm using the task in my grunt tasks folder and I didn't want team members to have to run npm install every time.

@yatskevich yeah I figured you grouped it by type to suit your workflow. I guess the ideal is the user can specify any path they want and things end up in there. I don't know if I'll have time this weekend to work on it but I think ultimately that's the way to go.

**Comment by robdodson** [comment]
I'm going to close this and try to submit a new request on a feature branch

**Pull request closed without merging**
