### PR TITLE
If property name is not existent on component.json default to property main on package.json

### PR DESCRIPTION
**Pull request by mitermayer**
...ain on package.json

### CODE REVIEW

**Comment by mitermayer** [comment]
best way to test this is using a component.json file that include backbone. Backbone doesnt have a component.json file but it does have the main property on the package.json referencing the main file

**Comment by benjamincox** [comment]
I hope this request is merged soon!

That said, it does raise a bit of a concern due to my own ignorance.  

Bower, itself, installs backbone just fine using 'bower install'.  I'm not clear on why wrapping that in this grunt task is causing it to fail?  Is the task trying to do too much?  

Can't it just let Bower figure out how to resolve things?

**Comment by yatskevich** [comment]
@benjamincox Backbone can be installed just fine using `grunt-bower-task`. If you do not specify explicit resources in `exportsOverride` section, then the whole repo will be copied to `lib` directory (it's default Bower behavior).

@mitermayer You are right. A lot of Bower packages lack `component.json`. Also most of them lack `package.json`. So falling back to `package.json` is not the best option for Bower packages. Thoughts?

**Comment by mitermayer** [comment]
I think we should try package.json than name guessing based on the repo with some regex and fall back on the end to full folder but saving it on a different location and displaying a warning to alert user to manualy grab files

**Comment by benjamincox** [comment]
I keep getting the following:

...
bower installing underscore#1.4.4
bower installing widgets
bower installing backbone#0.9.10
Fatal error: ENOENT, no such file or directory 'components/backbone'

Sure enough, there's no components/backbone directory.  If I do 'bower install', instead, then this output doesn't take place and there IS a components/backbone directory afterward. This gist demonstrates:   https://gist.github.com/benjamincox/56454d18dfa1665bf1f3

That failure at the end causes the next Grunt step to fail, which is currently making us do 'bower install && grunt' for our CI server.

**Comment by benjamincox** [comment]
Hmmm.... figured out that this takes place when using targetDir = "./components" in my Gruntfile.  Any other targetDir value works just fine, including none (which then defaults to 'lib/').  

Trouble is, then I end up with two copies of everything:  lib/ and components/.  Their contents are identical.  Is it truly necessary to have two copies of everything right there in the working directory?  That seems a little absurd to me.

Oddly enough, although targetDir='./components' causes backbone not to be installed into components/, when using the default targetDir I end up backbone installed into both 'components/' and 'lib/'.

**Comment by mitermayer** [comment]
@yatskevich would be great if this could get merged or if this issue could get solved, thats the only thing that is putting me to use another grunt bower task.

**Comment by mitermayer** [comment]
@yatskevich I was thinking another approach that could be done besides using package.json is doing a regex and trying to find file by name example backbone, trying to find a file backbone.js and variants like Backbone.js what you reckon ? i think with the fallback of package.json and this we could tackle most of this issues.  Thats the approach that this other grunt pluggin have done: 
https://github.com/gyllstromk/grunt-bowerful

Would be great if this issue could be merged or if you could implement another fix for it.

**Comment by mallim** [comment]
:+1:  May I know what is the status for this issue? Thanks

**Comment by yatskevich** [comment]
@benjamincox 
In the recent version of the plugin we support `cleanBowerDir` option which will clean the `components` dir after installing components into `lib`. These will prevent you from having two copies.

@mitermayer 
If you have troubles with Backbone installation, then try this config:
**bower.json**/**component.json**

```
{
    "name": "bootstrap-app",
    "version": "0.0.1",
    "dependencies": {
        "marionette": "1.0.0-rc2" // marionette depends on backbone
    },
    "exportsOverride": {
        "backbone": {
            "js": "backbone.js"
        },
    }
}
```

Any library that is not a Bower component can be described in `exportsOverride` section. In this section you can explicitly declare files you need in your `lib` folder.

**Comment by fantactuka** [comment]
Here's a gist https://gist.github.com/5808206 that downloads backbone, jquery, bootstrap and copies it into `targetDir` using `exporsOverride` option. Example shows how we can define files that we want to be copied from components.

``` bash
git clone https://gist.github.com/5808206.git grunt-bower-task-test
cd grunt-bower-task-test
npm install
grunt bower:install
```

We don't need code to "guess" the component name (from `package.json`, git repo name, or whatever else), since we can explicitly define files that we need from particular repository whether it has component/bower.js or not.

Let us know if you still have problems installing any components.

**Pull request closed without merging**
