### PR TITLE
bower.config.json is obsolete

### PR DESCRIPTION
**Pull request by benjamine**
As pointed out by:
https://github.com/bower/bower/blob/e1d77e12b97a6ca025c18b1d7ddf617636c39ed6/lib/config.js#L5
bower.config.json is no longer supported.
looking around bower source code it seems that assuming 'bower.json' is safe enough.
I fixed the tests accordingly.

### CODE REVIEW

**Comment by yatskevich** [comment]
@benjamine This PR is already covered by #57, isn't it?

**Comment by benjamine** [comment]
yes, that one fixed the problem, so this it's not really needed. 
althought if you want, I think I would still remove that property from the mock (as it doesn't exists for real anymore) and rename all those component.json as bower.json on fixtures.

**Comment by yatskevich** [comment]
True. :+1: 

By the way - we are going to rewrite tests, because it's clear now they are testing too much but still let some bugs to slip through. Are you ready to help? :)

**Comment by benjamine** [comment]
cool, if I may suggest I'd give a look at bdd style (eg. using mocha.js), but sorry I probably won't be able to help much with that expect for feedback, thx!

**Pull request closed without merging**
