### PR TITLE
fixes #61 - Adds Support for Bower Prune After Install

### LINKED ISSUE #61: Add 'prune' option
Bower has a 'prune' function that cleans my component directory of any libraries no longer listed in my bower.json file.   It would be nice if I could add that to my grunt file, to install new components, and prune out old ones I am no longer using.

### PR DESCRIPTION
**Pull request by sonicradish**

### CODE REVIEW

**Comment by cvn** [comment]
+1
@yatskevich Any chance you could merge this?

**Comment by timhettler** [comment]
+1 please merge

**Comment by chrishough** [comment]
+1 :smile_cat:

**Comment by cansin** [comment]
+1

**Comment by marcelboettcher** [comment]
+1

**Comment by dmccown1500** [comment]
+1

**Comment by rconley** [comment]
+1

**Comment by 8-bitTom** [comment]
+1

**Comment by codewithtyler** [comment]
@sonicradish My schedule clears up a good bit after Monday. I'll see about merging this in the next week or so.

**Pull request merged**
