### PR TITLE
Added support for keeping file structure

### LINKED ISSUE #21: Keep file structure when using exportsOverride
I load a requireJs based lib. As all files that mentioned in the exportsOverride block are put at the main level of `lib/js/myDependency/` I cant build the lib with requireJs as the require paths are broken now.

### PR DESCRIPTION
**Pull request by rasmusjp**
fixes #21

### CODE REVIEW

**Comment by yatskevich** [comment]
@rasmusjp Thanks for your effort! I'll take a look at the PR.

**Comment by gonzoyumo** [comment]
:+1:

**Comment by redoPop** [comment]
Not dug into this, but because of the path "tests/paths/first.js/first.js" I got an ENOTDIR when I tried byTypeKeepStructure with the requirejs package. Obviously I'll be weeding out test paths for actual use, but the same issue may affect other packages.

**Comment by lipis** [comment]
@yatskevich are you still taking look at that PR?! the support for the `layout(type, pkg, sourceDir)` is a must..!!

**Comment by willemave** [comment]
:+1:

**Comment by kenwarner** [comment]
thanks @rasmusjp

**Comment by dr-potato** [comment]
This would be a very useful addition. As of now grunt-bower-task breaks my Bourbon and Bourbon Neat imports, but this would fix it! Is there any chance of this pull request being accepted soon?

**Comment by yatskevich** [comment]
Guys, please take a look at version 0.4.0 of grunt-bower-task. @grawk has added a third parameter to a layout function - `source`, so it seems your use case can be implemented on top of it.

**Pull request closed without merging**
