### PR TITLE
Feature/support regex pkg

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
Hi, yatskevich.

I need to support regular expression for package.

if you accept my changes, we could write expandOverride like this.

``` js
{
    "name": "overrideRegexBowerConfiguration",
    "version": "0.0.0",
    "dependencies": {
        "bootstrap": "2.2.1",
        "jquery": "2.0.0"
    },
    "exportsOverride": {
        "bootstrap": {
            "js": "js/*.js",
            "scss": "lib/*.scss"
        },
        ".*": {
            "js": "**/*.js",
            "css": "**/*.css"
        }
    }
}
```

if you find any problems in my changes, please tell me.

Thanks.

### CODE REVIEW

**Comment by yatskevich** [comment]
@yosuke-furukawa, thanks for your PR! 

Just a small question. Do you use regex other than `.*` in your `exportsOverride` section? Any examples of groups of packages?

**Comment by yosuke-furukawa** [comment]
I just would like to use `.*` currently. but I would like to use regex other than `.*` in the future.

Because my team always install some client libraries using `bower install --save XXXX` and `grunt-bower-task`, but we sometimes forget to edit `exportsOverride`. So currently, we just use `.*` like this.

``` js
    "exportsOverride": {
        "bootstrap": {
            "js": "js/*.js",
            "css": "css/*.css"
        },
        "jquery": {
            "js": "*.js"
        },
        ".*": { // very helpful, we are free from editing bower.json.
            "js": "**/*.js",
            "css": "**/*.css"
        }
    }
```

In the future, I guess my team does not install client libraries so many times. 
If so, I would like to fix our libraries and keep our bower.json simple. Like this:

``` js
    "exportsOverride": {
        "underscore.*": { // underscore has underscore.string, underscore-partials
            "js": "**/*.js"
        },
        "jquery.*": {
            "js": "*.js"
        },
        ".*bootstrap.*": { // bootstrap-group has angular-ui-bootstrap, bootstrap-tour.
            "js": "**/*.js",
            "css": "**/*.css"
        },
    }
```

I don't want to write like this.

``` js
    "exportsOverride": {
        "underscore.string": {
            "js": "**/*.js"
        },
        "underscore-partials": {
            "js": "**/*.js"
        },
        "underscore-xxxxxx": {
            "js": "**/*.js"
        },
        ...
        "jquery": {
            "js": "*.js"
        },
        "jquery-ui": {
            "js": "*.js"
        },
        "jquery-xxxxxx": {
            "js": "*.js"
        },
        ...
    }
```

so we need this changes.

**Comment by yosuke-furukawa** [comment]
I guess you are saying about [bower_assets.js#L37](https://github.com/yosuke-furukawa/grunt-bower-task/blob/6d5d49f6cae3d26a433d8970249daf5495f5330f/tasks/lib/bower_assets.js#L37)?

(If it is wrong, please specify more precisely.)

I should copy the overrides args to be better. 

``` js
BowerAssets.prototype.mergePaths = function(allPaths, overrides) {
  var overrides = _.clone(overrides);
```

**Comment by fantactuka** [comment]
Exactly :)

**Comment by yosuke-furukawa** [comment]
Thanks for your comment! :)

**Comment by yatskevich** [comment]
I got you. This will be a good addition to the task.

So, there are a couple of comments regarding PR:
- You can safely delete most of the files in tests fixtures (jquery sources), or at least truncate content of these files because it's irrelevant to the test and task in particular.
- It would be great if you document this new feature in README.md

Also, I need time to review the code more carefully. I'll add comments later.

**Comment by yosuke-furukawa** [comment]
@yatskevich 

sure. I'm going to change them soon.

@fantactuka 

Hm, that is a lack of my consideration.
Ideally, regex evaluates by defined order in bower.json.
BUT, I think key order is not guaranteed.

So, I will sort JSON keys by length.

if json is defined as follows,

``` js
    "exportsOverride": {
        ".*": {
            "js": "**/*.js"
        },
        "bootstrap.*": {
            "js": "**/*.js",
            "css": "**/*.css"
        },
        "jquery.*": {
            "js": "*.js"
        },

    }
```

I am considering about the evaluated orders are `bootstrap.*`, `jquery.*`, `.*`.

so I will change,

``` js
var sortedKeys = copyOverrides.keys().sort(function(a, b) {
  return a.length < b.length;
});
_(sortedKeys).each(function(key) {
  var reg = new RegExp(key, 'gi');
  if (pkg.match(reg)) {
    _(copyOverrides[key]).each(createExpandedPath);
  }
});
```

**Comment by fantactuka** [comment]
I guess in node keys order is the same as declared. But I'm worries about a little different part of that: per current code if item matches 2 (3, 4, ...) regular expressions — it will be processed once per each, while I'd expect it will only go through the first matched. 

For matching priority I'd say — "first declared — first used" should be fine

Thoughts?

(and we also can wait for @yatskevich opinion)

**Comment by yosuke-furukawa** [comment]
I agree with @fantactuka opinion.

i can fix it easily, like this:

``` js
      _(copyOverrides).each(function(override, key) {
        var reg = new RegExp(key, 'gi');
        if (pkg.match(reg)) {
          _(override).each(createExpandedPath);
          // exit each loop.
          return false;
        }
      });
```

i would like to hear @yatskevich opinion.

**Comment by yosuke-furukawa** [comment]
Hi @fantactuka , @yatskevich 

I added a description about regex feature in README.md.
And I fixed loop error.

Please review them when you get a chance.

**Comment by yatskevich** [comment]
@yosuke-furukawa we had a long discussion with @fantactuka and here is our consolidated vision :)

We've realized that treating every entry (component name) in the `exportsOverride` as regex will be a good idea - such uniform approach will simplify the code and understanding of the feature by target users. 

At the same time one would like to keep things simple for common use-cases - for exact matches. Given that every entry is converted to regex we have to escape (?) symbols which have special meaning in regex - `.` (dot) is one of them. But what if the `.` is part of regex, not an exact match? This issue led us to a conclusion that it's required to indicated regexes _explicitly_ somehow.

Than we've analyzed your use-case and saw that it's more about wildcard support. That's the feature we can focus on right now.

**Wildcard support**
Example:

``` json
{
  "exportsOverride": {
    "bootstrap.*": {
      "js": "**/*.js",
      "css": "**/*.css"
    },
    "*": {
      "js": "**/*.js"
    }
  }
}
```

Spec:
- Entries are checked from top to bottom, the first match will be applied.
- Every exact match entry will be converted to a regex with escaped special symbols
- Entry with `*` (e.g. `"bootstrap.*"`) will have every special symbol escaped and `*` replaced with `.+` (so final regex may look like `/bootstrap\..+/`. That means `bootstrap.dot` will match while `bootstrap-dash` won't.

**Regex support**
If you want to add full regex support than it'll be required to explicitly indicate regex using JavaScript-like regex literal:

``` json
{
  "exportsOverride": {
    "/jquery.*/": {
      "js": "**/*.js"     
    }
  }
}
```

In this case entry will be converted to a regex directly: `"/jquery.*/"` -> `new RegExp("jquery.*")`

Thoughts?

**Comment by fantactuka** [comment]
I think in general implementation might be like this: http://jsfiddle.net/fantactuka/j6mMe/

**Comment by yosuke-furukawa** [comment]
@yatskevich @fantactuka 
Thanks for your discussion and writing samples.
I think this specification is really good.
I will implement this ASAP.

**Comment by fantactuka** [comment]
@yosuke-furukawa Let us know if we can provide any help — feature itself seems to be very cool, so highly interested it to go live :)

**Comment by yosuke-furukawa** [comment]
I implemented the feature, but I am not sure my implementation is simple and elegant.
If you have refactoring ideas, please teach me.

**Comment by yatskevich** [comment]
@yosuke-furukawa wonderful! We've reviewed your PR with @fantactuka - it's good to merge. 

Sure, there are some slight issues that we can fix together after the merge. If you'd like to do refactorings yourself, then we can postpone the merge and leave comments in code. What do you prefer?

**Comment by yosuke-furukawa** [comment]
@yatskevich @fantactuka 
Thanks for your review! No problem to merge. 
And I added the description for wildcard in README.md.

If you can accept the all changes, please merge this.

**Comment by fantactuka** [comment]
Today we had perfect case where this feature would have been very useful, so thanks again for idea and implementation :+1:

**Pull request merged**
