### PR TITLE
Paths refactor

### PR DESCRIPTION
**Pull request by robdodson**
Using this approach any override can be specified, including the same folders. So you could bundle everything however you like. If no override path is specified it will just default to the pkg.

``` json
{
  "name": "simple-bower",
  "version": "0.0.0",
  "dependencies": {
    "bootstrap": "~2.2.2",
    "prettify": "https://github.com/robdodson/prettify.git"
  },
  "exportsOverride": {
    "bootstrap": {
      "path/to/less": "less/*.less",
      "path/to/js": "js/*.js"
    },
    "prettify": {
      "path/to/less": "prettify.css",
      "path/to/js": "prettify.js"
    }
  }
}
```

### CODE REVIEW

**Comment by robdodson** [comment]
I also added support for the `.bowerrc` file. So if a .bowerrc exists it'll look to its `directory` instead of the previous hardcoded path of `components`

**Comment by robdodson** [comment]
ping

**Comment by mitermayer** [comment]
I think this is a great addition since you will be able to install things on different folders. I hope it gets merged :)

**Comment by robdodson** [comment]
I noticed today that there seems to be an issue with targetDir so I need to look into that. Another commit will be forthcoming...

**Comment by robdodson** [comment]
I take it back...everything seems to be working fine. Not sure what I was seeing before. Maybe I needed a cup of coffee or something :)

Hopefully this is good to go, @yatskevich ?

**Comment by yatskevich** [comment]
@robdodson I've examined your changes and it seems that existing behavior is changed.
If you specify:

``` json
{
  "exportsOverride": { 
    "bootstrap": {
      "less": "less/*.less"      
    }
  }
}
```

files will be copied to `lib/less` instead of desired `lib/less/bootstrap`. Otherwise you have to use `less/bootstrap` as a type.

By the way, what is your use case? We can discuss it via email if you wish :)

**Comment by robdodson** [comment]
@yatskevich yeah I did that on purpose to allow you to specify any path you want.

For instance you can do:

``` json
{
  "exportsOverride": { 
    "bootstrap": {                            // sets cwd
      "less": "less/*.less",                  // installs ./lib/less
      "js/bootstrap": "js/*.js"               // installs ./lib/js/bootstrap  <--- yatskevich's preferred structure
      "bootstrap/img": "img/*.png"            // installs ./lib/bootstrap/img  <-- robdodson's preferred structure
    }
  }
}
```

In my project I like to use the bower structure of namespacing everything first:

```
components/
  bootstrap/
    less/
    js/
  jquery/
  underscore/
```

whereas the current version of grunt-bower-task tries to inject the package name at the end of whatever override path you declare.

```
  less/
    bootstrap/
    font-awesome/
  js/
    bootstrap/
    jquery/
  img/
```

so I figured this was the smallest code change I could make to allow both structures. Basically it no longer tries to automagically inject the pkg, it literally installs to whatever path you spell out.

**Comment by yatskevich** [comment]
@robdodson I've realized that we can use [Strategy pattern](http://en.wikipedia.org/wiki/Strategy_pattern) here.

Let's add a configuration option for the task named `layout` which will specify what kind of directory structure you want. 
The simplest version may look like:

``` javascript
...
bower : {
  install: {
    options: {
      layout: 'byComponent' // your desired layout
    }
  }
}
...
```

I see two predefined strategies - `byComponent` and `byType`.

We can go further and specify layout as a function of (type, component):

``` javascript
var path = require('path');
...
  layout: function(type, component) {
    var renamedType = type;
    if (type == 'js') renamedType = 'javascripts';
    else if (type == 'css') renamedType = 'stylesheets';
    return path.join(component, renamedType);
  }
...
```

Named layouts may be implemented as simple functions as part of the task.

What do you think about this solution?

**Comment by robdodson** [comment]
Hm, you might still be locking people into predefined paths that they don't want.

While my patch requires a little extra typing I think it gives you the flexibility to use any structure you like.

**Comment by yatskevich** [comment]
The solution described above was implemented in 84c4b2bbd927. This feature will be available in 0.2.0 version.

**Pull request closed without merging**
