### PR TITLE
Add filtering options via wrench

### PR DESCRIPTION
**Pull request by xzyfer**
This builds upon #105 allowing users to pass `include`, and `exclude` options to wrench.

I've updated the readme to reflect these new options.

### CODE REVIEW

**Comment by xzyfer** [comment]
Ignore the first commit. It'll go away automatically when #105 is merged.

**Comment by xzyfer** [comment]
Any thoughts on this?

**Comment by codewithtyler** [comment]
@xzyfer we recently switched from wrench to the [fs-extra](https://github.com/jprichardson/node-fs-extra) packge. Seeing as filtering is on the roadmap for an upcomding release if you'd like to update your PR to use the new package I'd be happy to review and merge it.

**Comment by xzyfer** [comment]
Sorry I have not used this project in years. This probably doesn't make sense without wrench anyway. Feel free to close this issue.

**Pull request closed without merging**
